name: date_picker
description: A custom date picker that allows you to pick day / month / year as well as single / range / multiple selections.
version: 1.0.0
homepage: https://github.com/ricnaaru

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  google_fonts: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
